# Generated by Django 4.1.3 on 2022-11-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_restaurantlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='total_like',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
