# Generated by Django 4.1.3 on 2022-11-08 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_restaurant_total_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='like_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
