# Generated by Django 4.1.3 on 2022-11-08 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_restaurant_like_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='like_by',
        ),
        migrations.AddField(
            model_name='restaurantlike',
            name='like_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='restaurantlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
