# Generated by Django 4.1.3 on 2022-11-09 04:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_restaurant_like_by_restaurantlike_like_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantlike',
            name='like_by',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='like_by',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
